sudo: false
language: python
python:
  - 2.7
  - 3.5
install:
  - pip install tox-travis
  - pip install cookiecutter
script:
  - cookiecutter -o /tmp/ --no-input .
  - cd /tmp/myapp
  - git init
  - tox
